// we have to create password generator
// which takes how much long password do you want i.e 4 digit , 6 digit or 8 digit 3 choices
// there could be following variety of password where your select which one do he like
// 1. easy : only numbers
// 2. medium : number and characters
// 3. hard : numbers , characters and symbols as well
// 4. Funny one : FUNNY in which we have to just get this array of funny passwords and randomly generate one of them.

// Array For Funny passwords :

// const Funny = [
//   "lastdudeisakeeper4real",
//   "kittysoup",
//   "2BBlue",
//   "cadet",
//   "youwontguessthisone",
//   "marybakereddy",
//   "jordannike",
//   "i12kissu",
//   "password123",
//   "myonlypassword",
//   "spanky",
//   "cowboysvstexans",
//   "vERtiOus",
//   "chaunukkah",
//   "IAmACompleteIdiot",
//   "Click Here for Wifi",
//   "The House of Black and WiFi",
//   " WiFestores",
//   "Useit@yourrisk*0",
//   "yetanotherpassword",
//   "youmoron",
//   "doubleclick",
//   "harley",
//   "SmartToilet8000",
//   " Not the Wifi You’re Looking For",
//   " Whose Car Alarm is That",
//   "The Internet",
//   "  buster",
//   "whatpassword",
//   " AccessDenied4u",
//   "House of Donald trump",
//   "Silence of the LANwghfluffy72Is2Short",
//   "gojihad",
//   ,
//   "omghi2u",
//   "ghanta",
//   "bond007",
//   "mypassword",
//   "Threetimes",
//   "pinkfluffybunny",
//   "iamnottellingyoumypw",
//   "iloveme",
//   "iamforgetful",
//   "kwanzaa",
//   "iforgotagain",
//   "swordfish",
//   "TheyRWatching",
//   "iForgot",
//   "qwertyui",
//   "honeybump",
//   "inSSIDer",
//   "Byte Me",
//   "You Fart Pretty Loud",
//   "DoUthinkitsfree$0",
//   "WiFi@40$dPH",
//   "mateRIST",
//   "lookatme",
//   "Nothing",
//   "MisterNasty12",
//   "strucant",
//   "giiglepig",
//   "justkeepswimmin",
//   "Dunder MiffLAN",
//   "Bandwidth Together",
//   "Girls Gone Wireless",
//   " Drop It Like It’s Hotspot",
//   "It Burns When IP",
//   "Abraham Linksys",
//   "I Did Your Wifi Last Night",
//   "No LAN for the Wicked",
//   "xxxxxxxx",
//   "MickeyMinnieGoofyPluto",
//   " Asd1234",
//   "baseballandfootball",
//   "123neverguess",
//   "luckyFan",
//   "EXgENiNg",
//   "Itnowknow",
//   "password",
//   "Qwerty11",
//   "I Slept With Your WiFi",
//   "YouarenotAllowed2Use",
//   " YourDogShitsInMyYard",
//   "New England Clam Router",
//   "killergirl",
//   "hairyback",
//   "turkey02",
//   "cantremember",
//   "dontaskdonttell",
//   "batmanandrobbin",
//   "batmanandrobbin",
//   'Very slow internet',
//   'Please Wait…',
//   'Amish Rebel',
//   'Pay for WiFi',
//   '77777777',
//   'Now you see me…',
//  ' Pay and use',
//   'Shutting Down',
//   '0000000000',
//   'This is not Free',
//   'Harley',
//   '$10 an hour',
//   'Searching for GF',
//   'Wifi Fever',
//   'coming soon!',
//   'No Internet Access',
//   'Open Sesame',
//  ' Let them use it',
//   'jewishnipple',
//   'I now know',
//   'fluffy72Is2Short',
//   'Go Go Gadget Internet',
//   'Don\’t Snoop',
//  ' WiFi@40$dPH',
//   'Ye old Internet',
//   'Don\’t Snoop',
//   'Matthew',
//   'not working',
//   'Pornonly@007',
//   'Life on the Line',
//   'AAAAAAAAAA',
//   'Jordan',
//   'DontEvenTry2Hack!',
//   'Pay and use',
//   'Hacker Here',
//  ' Wi-FI Fo Fum',
//   'Net gear',
//  ' UnprotectedCex@18',
//   'Connection timed out',
//   'Robert',
//  ' Iam18@Loveyou',
//   'Network is down',
//   'I Stalk You',
//   'Useit@yourrisk*0',
//   'asshole',
//  ' Wi of the Figer',
//   'Networkis2Slow@',
//   'Printer Only',
//   'adolftheclown',
//   'I’m watching you',
//  ' giving',
//   'Ye old In,ternet',
//   'Wait4sometime@',
//   'Please use me',
//   '143@ILUILU',
//   'GrEssatE',
//   'I Love you ,my wifi',
//  ' Free wifi',
//   'pwned you',
//   'Nacho WiFi',
//   '1234',
//   'Infected Wifi',
//   'Bring Bear & Women',
//   'Call Me Darling',
//   'Free Wifi',
//   'Default',
//  ' NoWiFi4you',
//   "Switch On WIFI",
//  '654321',
//   'Russian Hackers'
// ];

// console.log(Funny.length);
